<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EventStore.Abstractions\EventStore.Abstractions.csproj" />
    <ProjectReference Include="..\EventStore.SchemaRegistry\EventStore.SchemaRegistry.csproj" />
    <ProjectReference Include="..\EventStore.Erasure\EventStore.Erasure.csproj" />
    <ProjectReference Include="..\EventStore.Masking\EventStore.Masking.csproj" />
    <ProjectReference Include="..\EventStore.Router\EventStore.Router.csproj" />
    <ProjectReference Include="..\EventStore.WorkerWakeSignal\EventStore.WorkerWakeSignal.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
