// <auto-generated />
using System;
using EventStore.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventStore.Persistence.Migrations.Postgres.Migrations
{
    [DbContext(typeof(EventStoreContext))]
    [Migration("20260810214923_AddFeatureFlagState")]
    partial class AddFeatureFlagState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventStore.Domain.AccessLog.AccessLogEntry", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<DateTimeOffset>("AccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChainHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("GrantRef")
                        .HasColumnType("uuid");

                    b.Property<string>("ReaderActorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReaderTrustBasis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResourceRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ViewAccessed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("ReaderActorId");

                    b.ToTable("AccessLogEntries");
                });

            modelBuilder.Entity("EventStore.Domain.EntityStore.EntityErasureKey", b =>
                {
                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("BackendName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ErasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EntityId");

                    b.ToTable("EntityErasureKeys");
                });

            modelBuilder.Entity("EventStore.Domain.EntityStore.EntityStoreRow", b =>
                {
                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("AuthorityStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Extensions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastAppliedLogicalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastAppliedOriginId")
                        .HasColumnType("text");

                    b.Property<long>("LastAppliedSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<bool>("LateArrivalFlag")
                        .HasColumnType("boolean");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ShardKey")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("EntityId");

                    b.HasIndex("EntityType");

                    b.ToTable("EntityStore");
                });

            modelBuilder.Entity("EventStore.Domain.EntityStore.LiveEntityStoreRow", b =>
                {
                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("AuthorityStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Extensions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("LastAppliedSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EntityId");

                    b.HasIndex("EntityType");

                    b.ToTable("LiveEntityStore");
                });

            modelBuilder.Entity("EventStore.Domain.EntityStore.LocalErasureKeyMaterial", b =>
                {
                    b.Property<string>("KeyReference")
                        .HasColumnType("text");

                    b.Property<bool>("Destroyed")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("WrappedKey")
                        .HasColumnType("bytea");

                    b.HasKey("KeyReference");

                    b.ToTable("LocalErasureKeyMaterials");
                });

            modelBuilder.Entity("EventStore.Domain.EventLog.EventParent", b =>
                {
                    b.Property<Guid>("ChildEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParentEventId")
                        .HasColumnType("uuid");

                    b.HasKey("ChildEventId", "ParentEventId");

                    b.HasIndex("ChildEventId");

                    b.HasIndex("ParentEventId");

                    b.ToTable("EventParents");
                });

            modelBuilder.Entity("EventStore.Domain.EventLog.StoredEvent", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AttestedActorId")
                        .HasColumnType("text");

                    b.Property<string>("AttestedClaims")
                        .HasColumnType("text");

                    b.Property<Guid?>("AuthorityDecisionRef")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorityStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChainHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ConflictFlag")
                        .HasColumnType("boolean");

                    b.Property<int>("DerivationHopCount")
                        .HasColumnType("integer");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<int>("EventKind")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ExpectedVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("ImportedFrom")
                        .HasColumnType("text");

                    b.Property<bool>("LateArrivalFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("LogicalClock")
                        .HasColumnType("text");

                    b.Property<Guid?>("MaterializationOfEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginId")
                        .HasColumnType("text");

                    b.Property<string>("OriginalChainHash")
                        .HasColumnType("text");

                    b.Property<long?>("OriginalSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchemaStatus")
                        .HasColumnType("text");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Signature")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelemetryPointer")
                        .HasColumnType("text");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EntityId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EventStore.Domain.FeatureFlags.FeatureFlagState", b =>
                {
                    b.Property<string>("AppId")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<long>("LastAppliedSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AppId", "Key");

                    b.ToTable("FeatureFlags");
                });

            modelBuilder.Entity("EventStore.Domain.Replication.PeerSyncCursor", b =>
                {
                    b.Property<string>("PeerId")
                        .HasColumnType("text");

                    b.Property<long>("LastAckedSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<long>("LastReceivedSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastSyncAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSyncSuccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PeerId");

                    b.ToTable("PeerSyncCursors");
                });

            modelBuilder.Entity("EventStore.Domain.SchemaRegistry.DerivationCursor", b =>
                {
                    b.Property<string>("AppId")
                        .HasColumnType("text");

                    b.Property<string>("DerivationName")
                        .HasColumnType("text");

                    b.Property<string>("SourceEventType")
                        .HasColumnType("text");

                    b.Property<long>("LastProcessedSequenceNumber")
                        .HasColumnType("bigint");

                    b.HasKey("AppId", "DerivationName", "SourceEventType");

                    b.ToTable("DerivationCursors");
                });

            modelBuilder.Entity("EventStore.Domain.SchemaRegistry.DerivationDefinition", b =>
                {
                    b.Property<string>("AppId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("BackfillMode")
                        .HasColumnType("integer");

                    b.Property<bool>("BackfillThroughDerivedSources")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JoinConditions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JoinTriggerMode")
                        .HasColumnType("integer");

                    b.Property<int>("MaxHopCount")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("PendingJoinTtl")
                        .HasColumnType("interval");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SelectFields")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sources")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AppId", "Name");

                    b.ToTable("DerivationDefinitions");
                });

            modelBuilder.Entity("EventStore.Domain.SchemaRegistry.EventTypeDefinition", b =>
                {
                    b.Property<string>("AppId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<int>("ChangeKind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeprecatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DowncastToPrevious")
                        .HasColumnType("text");

                    b.Property<string>("EntityIdField")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JsonSchema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParentValidationMode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RejectionBehavior")
                        .HasColumnType("integer");

                    b.Property<string>("RequiredClaims")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequiredSignature")
                        .HasColumnType("text");

                    b.Property<string>("UpcastFromPrevious")
                        .HasColumnType("text");

                    b.HasKey("AppId", "Name", "Version");

                    b.ToTable("EventTypeDefinitions");
                });

            modelBuilder.Entity("EventStore.Domain.SchemaRegistry.FilterableField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DataType")
                        .HasColumnType("integer");

                    b.Property<string>("EventTypeAppId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EventTypeVersion")
                        .HasColumnType("integer");

                    b.Property<bool>("IsIndexed")
                        .HasColumnType("boolean");

                    b.Property<string>("JsonPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventTypeAppId", "EventTypeName", "EventTypeVersion");

                    b.ToTable("FilterableFields");
                });

            modelBuilder.Entity("EventStore.Domain.SchemaRegistry.PendingJoinState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArrivedSourcesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DerivationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpiredReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JoinKeyValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("AppId", "DerivationName", "JoinKeyValue");

                    b.ToTable("PendingJoinStates");
                });

            modelBuilder.Entity("EventStore.Domain.Streaming.Attachment", b =>
                {
                    b.Property<string>("ContentHash")
                        .HasColumnType("text");

                    b.Property<byte[]>("Bytes")
                        .HasColumnType("bytea");

                    b.Property<string>("ChunkIndex")
                        .HasColumnType("text");

                    b.Property<string>("ContentProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ContentProviderRef")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequiredPublishClaim")
                        .HasColumnType("text");

                    b.Property<string>("RequiredReadClaim")
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ContentHash");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("EventStore.Domain.Streaming.AttachmentRef", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("EntityId");

                    b.HasIndex("EventId");

                    b.ToTable("AttachmentRefs");
                });

            modelBuilder.Entity("EventStore.Domain.Streaming.RedactedRange", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FromTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<char?>("MaskChar")
                        .HasColumnType("character(1)");

                    b.Property<bool>("PreserveSeparators")
                        .HasColumnType("boolean");

                    b.Property<string>("RequiredClaim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ShowFirst")
                        .HasColumnType("integer");

                    b.Property<int?>("ShowLast")
                        .HasColumnType("integer");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ToTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ChannelId", "FromTimestamp");

                    b.ToTable("RedactedRanges");
                });

            modelBuilder.Entity("EventStore.Domain.Streaming.TelemetryChannel", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasColumnType("text");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ContentKind")
                        .HasColumnType("integer");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastAppliedLogicalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastBatchReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSampleTimestampReceived")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MimeType")
                        .HasColumnType("text");

                    b.Property<int>("Origin")
                        .HasColumnType("integer");

                    b.Property<string>("RequiredReadClaim")
                        .HasColumnType("text");

                    b.Property<long?>("SampleIntervalMicros")
                        .HasColumnType("bigint");

                    b.Property<int?>("SampleType")
                        .HasColumnType("integer");

                    b.Property<string>("SourceChannelIds")
                        .HasColumnType("text");

                    b.Property<string>("ThreadId")
                        .HasColumnType("text");

                    b.Property<string>("TransformKind")
                        .HasColumnType("text");

                    b.HasKey("ChannelId");

                    b.HasIndex("ThreadId");

                    b.ToTable("TelemetryChannels");
                });

            modelBuilder.Entity("EventStore.Domain.Streaming.TelemetrySample", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LateArrivalFlag")
                        .HasColumnType("boolean");

                    b.Property<long?>("MonotonicElapsedMicros")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Value")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("ChannelId", "Timestamp");

                    b.ToTable("TelemetrySamples");
                });

            modelBuilder.Entity("EventStore.Domain.Views.ViewDefinition", b =>
                {
                    b.Property<string>("EntityType")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<int>("ViewKind")
                        .HasColumnType("integer");

                    b.Property<string>("CompatibleSchemaVersions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeprecatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemplateContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EntityType", "Version", "ViewKind");

                    b.ToTable("ViewDefinitions");
                });

            modelBuilder.Entity("EventStore.Domain.SchemaRegistry.FilterableField", b =>
                {
                    b.HasOne("EventStore.Domain.SchemaRegistry.EventTypeDefinition", null)
                        .WithMany("FilterableFields")
                        .HasForeignKey("EventTypeAppId", "EventTypeName", "EventTypeVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventStore.Domain.SchemaRegistry.EventTypeDefinition", b =>
                {
                    b.Navigation("FilterableFields");
                });
#pragma warning restore 612, 618
        }
    }
}
