using System.Text;
using Microsoft.Playwright;

namespace EventStore.E2ETests;

// The screenshot-capture-to-markdown-assembly pipeline this whole project
// exists for (TODO.md, direct request: "scripted so these can be updated
// and extended as needed" -- re-running the owning [TestMethod] via
// `dotnet test` regenerates the playbook end to end, no manual assembly
// step). RecordStepAsync takes a screenshot and a human-readable caption
// at each meaningful point in a real Playwright walkthrough;
// WriteMarkdownAsync assembles everything captured so far into one
// playbook file, embedding each screenshot next to its caption, in the
// order steps were recorded.
//
// Naming convention (direct request, confirmed with the user):
// {workflow}-{feature doc name}.md, e.g. docs/playbooks/vitals/
// workflow-a-patient-enrollment-and-informed-consent.md -- reuses each
// domain README's own existing Workflow lettering (Vitals A-D, Meridian
// A-C) rather than inventing a new "epic" concept this project doesn't
// otherwise have. Screenshots live in a sibling folder matching the
// markdown file's own basename (e.g. .../workflow-a-patient-enrollment-
// and-informed-consent/step-01.png), so the whole playbook -- prose and
// images together -- is one self-contained pair to add, move, or delete.
public class PlaybookRecorder
{
    private readonly string _markdownPath;
    private readonly string _assetDirectoryName;
    private readonly string _assetDirectoryPath;
    private readonly List<(string ScreenshotFileName, string Caption)> _steps = [];

    public PlaybookRecorder(string markdownPath)
    {
        _markdownPath = markdownPath;
        _assetDirectoryName = Path.GetFileNameWithoutExtension(markdownPath);
        _assetDirectoryPath = Path.Combine(Path.GetDirectoryName(markdownPath)!, _assetDirectoryName);
    }

    public async Task RecordStepAsync(IPage page, string caption)
    {
        Directory.CreateDirectory(_assetDirectoryPath);
        var fileName = $"step-{_steps.Count + 1:D2}.png";
        // FullPage: true -- a viewport-only screenshot silently crops
        // whatever's currently scrolled out of view. Found only by
        // actually reviewing a real screenshot: the Lineage & Playback
        // panel's own reconstructed-data result rendered successfully
        // (the test's own ToBeVisibleAsync assertion passed -- Playwright's
        // "visible" doesn't require being within the current scroll
        // position) but sat entirely below the fold on a page that grew
        // taller than one viewport, so the captured image never showed it
        // at all despite the step genuinely having worked.
        await page.ScreenshotAsync(new PageScreenshotOptions { Path = Path.Combine(_assetDirectoryPath, fileName), FullPage = true });
        _steps.Add((fileName, caption));
    }

    // Optional -- a PlantUML sequence diagram showing the general
    // business-process flow this playbook's own screenshots walk
    // through (with alt/opt blocks for a real alternate path, e.g. a
    // rejection, a step-up challenge, or an unmatched-vs-matched
    // branch), placed right after the generated-by note and before
    // Step 1. Written by hand per playbook test (direct request,
    // TODO.md-adjacent) rather than derived from the screenshots
    // themselves -- there's no mechanical way to produce a sequence
    // diagram from a page's own DOM, and the underlying business
    // process is exactly the kind of thing a human author decides how
    // to depict, the same reasoning every other PlantUML diagram in
    // this repo is hand-authored rather than generated. Follows this
    // repo's own standing PlantUML convention (CLAUDE.md): no external
    // `!include`, ever.
    public async Task WriteMarkdownAsync(string title, string? sequenceDiagramPlantUml = null)
    {
        if (_steps.Count == 0)
            throw new InvalidOperationException("No steps recorded -- RecordStepAsync must be called at least once before WriteMarkdownAsync.");

        var sb = new StringBuilder();
        sb.AppendLine($"# {title}");
        sb.AppendLine();
        sb.AppendLine("_Generated by `EventStore.E2ETests` against a real running deployment --" +
            " re-run `dotnet test tests/EventStore.E2ETests` to regenerate. Don't hand-edit this" +
            " file directly; edit the owning test's own step captions instead, or the content" +
            " will be overwritten on the next run._");
        sb.AppendLine();

        if (sequenceDiagramPlantUml is not null)
        {
            sb.AppendLine("## Sequence Diagram");
            sb.AppendLine();
            sb.AppendLine("```plantuml");
            sb.AppendLine(sequenceDiagramPlantUml.Trim());
            sb.AppendLine("```");
            sb.AppendLine();
        }

        for (var i = 0; i < _steps.Count; i++)
        {
            var (screenshotFileName, caption) = _steps[i];
            sb.AppendLine($"## Step {i + 1}. {caption}");
            sb.AppendLine();
            sb.AppendLine($"![{caption}]({_assetDirectoryName}/{screenshotFileName})");
            sb.AppendLine();
        }

        Directory.CreateDirectory(Path.GetDirectoryName(_markdownPath)!);
        await File.WriteAllTextAsync(_markdownPath, sb.ToString());
    }
}
