// <auto-generated />
using System;
using EventStore.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventStore.Persistence.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(EventStoreContext))]
    partial class EventStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("EventStore.Domain.AccessLog.AccessLogEntry", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AccessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChainHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GrantRef")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReaderActorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReaderTrustBasis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ViewAccessed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("ReaderActorId");

                    b.ToTable("AccessLogEntries");
                });

            modelBuilder.Entity("EventStore.Domain.EntityStore.EntityErasureKey", b =>
                {
                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackendName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ErasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EntityId");

                    b.ToTable("EntityErasureKeys");
                });

            modelBuilder.Entity("EventStore.Domain.EntityStore.EntityStoreRow", b =>
                {
                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorityStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Extensions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastAppliedLogicalTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastAppliedOriginId")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastAppliedSequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LateArrivalFlag")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShardKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntityId");

                    b.HasIndex("EntityType");

                    b.ToTable("EntityStore");
                });

            modelBuilder.Entity("EventStore.Domain.EntityStore.LiveEntityStoreRow", b =>
                {
                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorityStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Extensions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastAppliedSequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("EntityId");

                    b.HasIndex("EntityType");

                    b.ToTable("LiveEntityStore");
                });

            modelBuilder.Entity("EventStore.Domain.EntityStore.LocalErasureKeyMaterial", b =>
                {
                    b.Property<string>("KeyReference")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Destroyed")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("WrappedKey")
                        .HasColumnType("BLOB");

                    b.HasKey("KeyReference");

                    b.ToTable("LocalErasureKeyMaterials");
                });

            modelBuilder.Entity("EventStore.Domain.EventLog.EventParent", b =>
                {
                    b.Property<Guid>("ChildEventId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParentEventId")
                        .HasColumnType("TEXT");

                    b.HasKey("ChildEventId", "ParentEventId");

                    b.HasIndex("ChildEventId");

                    b.HasIndex("ParentEventId");

                    b.ToTable("EventParents");
                });

            modelBuilder.Entity("EventStore.Domain.EventLog.StoredEvent", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AttestedActorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttestedClaims")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuthorityDecisionRef")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorityStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChainHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConflictFlag")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DerivationHopCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpectedVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImportedFrom")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LateArrivalFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogicalClock")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MaterializationOfEventId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalChainHash")
                        .HasColumnType("TEXT");

                    b.Property<long?>("OriginalSequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaStatus")
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Signature")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelemetryPointer")
                        .HasColumnType("TEXT");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EntityId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EventStore.Domain.FeatureFlags.FeatureFlagState", b =>
                {
                    b.Property<string>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastAppliedSequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AppId", "Key");

                    b.ToTable("FeatureFlags");
                });

            modelBuilder.Entity("EventStore.Domain.LeaderElection.LeaderLease", b =>
                {
                    b.Property<string>("WorkerRole")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LeaseExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseHolderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkerRole");

                    b.ToTable("LeaderLeases");
                });

            modelBuilder.Entity("EventStore.Domain.Replication.AppResidencyPolicy", b =>
                {
                    b.Property<string>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedRegions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastAppliedSequenceNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppId");

                    b.ToTable("AppResidencyPolicies");
                });

            modelBuilder.Entity("EventStore.Domain.Replication.PeerSyncCursor", b =>
                {
                    b.Property<string>("PeerId")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastAckedSequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastReceivedSequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastSyncAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSyncSuccessAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PeerId");

                    b.ToTable("PeerSyncCursors");
                });

            modelBuilder.Entity("EventStore.Domain.SchemaRegistry.DerivationCursor", b =>
                {
                    b.Property<string>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DerivationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceEventType")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastProcessedSequenceNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("AppId", "DerivationName", "SourceEventType");

                    b.ToTable("DerivationCursors");
                });

            modelBuilder.Entity("EventStore.Domain.SchemaRegistry.DerivationDefinition", b =>
                {
                    b.Property<string>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("BackfillMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BackfillThroughDerivedSources")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JoinConditions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JoinTriggerMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHopCount")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("PendingJoinTtl")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectFields")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sources")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AppId", "Name");

                    b.ToTable("DerivationDefinitions");
                });

            modelBuilder.Entity("EventStore.Domain.SchemaRegistry.EventTypeDefinition", b =>
                {
                    b.Property<string>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChangeKind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DeprecatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DowncastToPrevious")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityIdField")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JsonSchema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentValidationMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RejectionBehavior")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequiredClaims")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredSignature")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpcastFromPrevious")
                        .HasColumnType("TEXT");

                    b.HasKey("AppId", "Name", "Version");

                    b.ToTable("EventTypeDefinitions");
                });

            modelBuilder.Entity("EventStore.Domain.SchemaRegistry.FilterableField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventTypeAppId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EventTypeVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsIndexed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JsonPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventTypeAppId", "EventTypeName", "EventTypeVersion");

                    b.ToTable("FilterableFields");
                });

            modelBuilder.Entity("EventStore.Domain.SchemaRegistry.PendingJoinState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArrivedSourcesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DerivationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiredReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("JoinKeyValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("AppId", "DerivationName", "JoinKeyValue");

                    b.ToTable("PendingJoinStates");
                });

            modelBuilder.Entity("EventStore.Domain.Streaming.Attachment", b =>
                {
                    b.Property<string>("ContentHash")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Bytes")
                        .HasColumnType("BLOB");

                    b.Property<string>("ChunkIndex")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentProviderRef")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastAccessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredPublishClaim")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredReadClaim")
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ContentHash");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("EventStore.Domain.Streaming.AttachmentRef", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("EntityId");

                    b.HasIndex("EventId");

                    b.ToTable("AttachmentRefs");
                });

            modelBuilder.Entity("EventStore.Domain.Streaming.RedactedRange", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FromTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<char?>("MaskChar")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PreserveSeparators")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequiredClaim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShowFirst")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShowLast")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ToTimestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("ChannelId", "FromTimestamp");

                    b.ToTable("RedactedRanges");
                });

            modelBuilder.Entity("EventStore.Domain.Streaming.TelemetryChannel", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastAppliedLogicalTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastBatchReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSampleTimestampReceived")
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .HasColumnType("TEXT");

                    b.Property<int>("Origin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequiredReadClaim")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SampleIntervalMicros")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SampleType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceChannelIds")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThreadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransformKind")
                        .HasColumnType("TEXT");

                    b.HasKey("ChannelId");

                    b.HasIndex("ThreadId");

                    b.ToTable("TelemetryChannels");
                });

            modelBuilder.Entity("EventStore.Domain.Streaming.TelemetrySample", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LateArrivalFlag")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MonotonicElapsedMicros")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Value")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("ChannelId", "Timestamp");

                    b.ToTable("TelemetrySamples");
                });

            modelBuilder.Entity("EventStore.Domain.Views.ViewDefinition", b =>
                {
                    b.Property<string>("EntityType")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ViewKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompatibleSchemaVersions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeprecatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EntityType", "Version", "ViewKind");

                    b.ToTable("ViewDefinitions");
                });

            modelBuilder.Entity("EventStore.Domain.Webhooks.WebhookDeliveryCursor", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastDeliveredSequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("TEXT");

                    b.HasKey("SubscriptionId");

                    b.ToTable("WebhookDeliveryCursors");
                });

            modelBuilder.Entity("EventStore.Domain.Webhooks.WebhookOutbox", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("EnqueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventPayloadSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SourceSequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("WebhookOutbox");
                });

            modelBuilder.Entity("EventStore.Domain.Webhooks.WebhookSubscription", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventTypes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FixedClaimsSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutboundAdapterKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousSigningSecret")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SigningSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SubscriptionId");

                    b.ToTable("WebhookSubscriptions");
                });

            modelBuilder.Entity("EventStore.Domain.SchemaRegistry.FilterableField", b =>
                {
                    b.HasOne("EventStore.Domain.SchemaRegistry.EventTypeDefinition", null)
                        .WithMany("FilterableFields")
                        .HasForeignKey("EventTypeAppId", "EventTypeName", "EventTypeVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventStore.Domain.SchemaRegistry.EventTypeDefinition", b =>
                {
                    b.Navigation("FilterableFields");
                });
#pragma warning restore 612, 618
        }
    }
}
