// <auto-generated />
using System;
using EventStore.Flows;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventStore.Flows.Migrations
{
    [DbContext(typeof(PendingTasksDbContext))]
    partial class PendingTasksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("EventStore.Flows.PendingTask", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlowName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredClaim")
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggeringEventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("PendingTasks");
                });

            modelBuilder.Entity("EventStore.Projections.Host.ProjectionCheckpoint", b =>
                {
                    b.Property<string>("ProjectionName")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSequenceNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectionName");

                    b.ToTable("Checkpoints");
                });

            modelBuilder.Entity("EventStore.Projections.Host.ProjectionSnapshot", b =>
                {
                    b.Property<string>("ProjectionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastAppliedSequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectionName", "Key");

                    b.ToTable("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
