<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EventStore.Abstractions\EventStore.Abstractions.csproj" />
    <ProjectReference Include="..\EventStore.Domain\EventStore.Domain.csproj" />
    <ProjectReference Include="..\EventStore.Persistence\EventStore.Persistence.csproj" />
    <ProjectReference Include="..\EventStore.SchemaRegistry\EventStore.SchemaRegistry.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="VaultSharp" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Azure.Security.KeyVault.Keys" />
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="AWSSDK.KeyManagementService" />
    <PackageReference Include="Google.Cloud.Kms.V1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
