// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Samples.Orders.Projections;

#nullable disable

namespace Samples.Orders.Projections.Migrations
{
    [DbContext(typeof(OrdersProjectionsDbContext))]
    partial class OrdersProjectionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("EventStore.Projections.Host.ProjectionCheckpoint", b =>
                {
                    b.Property<string>("ProjectionName")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSequenceNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectionName");

                    b.ToTable("Checkpoints");
                });

            modelBuilder.Entity("EventStore.Projections.Host.ProjectionSnapshot", b =>
                {
                    b.Property<string>("ProjectionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastAppliedSequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectionName", "Key");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("Samples.Orders.Projections.OrderSummary", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ShippedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId");

                    b.ToTable("OrderSummaries");
                });
#pragma warning restore 612, 618
        }
    }
}
